{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.systemloglib",
    "module": "systemloglib",
    "version": "1.0-20231128",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "systemloglib-1.0-20231128.aar",
          "url": "systemloglib-1.0-20231128.aar",
          "size": 49259,
          "sha512": "debb0b5a7638c418a4ee4201750f1479982f65622e1d975e547c16c115a5552610dd4cceb342a0823ce6ed7db30eaa99cf0ed09dfb451673bd67d5e7106ae2bf",
          "sha256": "4b870c9d545ec7c0b7fd5ffd4d1d64f3739b210d40ee72962ae985ac1f4baa13",
          "sha1": "f7de25f8c3dc1963a8fcdffcd0374bdafffc1570",
          "md5": "063b48c3bb55784eeb69edebac066836"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "systemloglib-1.0-20231128.aar",
          "url": "systemloglib-1.0-20231128.aar",
          "size": 49259,
          "sha512": "debb0b5a7638c418a4ee4201750f1479982f65622e1d975e547c16c115a5552610dd4cceb342a0823ce6ed7db30eaa99cf0ed09dfb451673bd67d5e7106ae2bf",
          "sha256": "4b870c9d545ec7c0b7fd5ffd4d1d64f3739b210d40ee72962ae985ac1f4baa13",
          "sha1": "f7de25f8c3dc1963a8fcdffcd0374bdafffc1570",
          "md5": "063b48c3bb55784eeb69edebac066836"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "systemloglib-1.0-20231128-sources.jar",
          "url": "systemloglib-1.0-20231128-sources.jar",
          "size": 9715,
          "sha512": "78c873d5eb3f68d1da52f19307e09f8a9854288690fdab2f837ff61f3bfbd596e91cf45dd2950c4db5f90c079c2def02b522985c6b19d8cd900c0e82f32a8fd3",
          "sha256": "e7e5869e32ea10c58b40ed9a9621c1b008a7edfab4f94eb5002fd0502d213f7b",
          "sha1": "47879c99e444b8b4e695c8d209e067ff098d387b",
          "md5": "3001e5363cee7a55bd1e0c615f825c6b"
        }
      ]
    }
  ]
}
